apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-echo-server
  template:
    metadata:
      labels:
        app: ws-echo-server
    spec:
      containers:
        - name: ws-echo-server
          image: jmalloc/echo-server:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: ws-echo-server-service
spec:
  ports:
    - name: ws-port
      port: 10010
      targetPort: 8080
  selector:
    app: ws-echo-server
  type: ClusterIP