apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:latest
          ports:
            - containerPort: 10000
              name: blob
            - containerPort: 10001
              name: queue
            - containerPort: 10002
              name: table
---
apiVersion: v1
kind: Service
metadata:
    name: azurite-service
spec:
  ports:
    - name: azurite-blob-port
      port: 10020
      targetPort: 10000
    - name: azurite-queue-port
      port: 10021
      targetPort: 10001
    - name: azurite-table-port
      port: 10022
      targetPort: 10002
  selector:
    app: azurite
  type: LoadBalancer